config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    post "/sign_up" => "devise/registrations#create"
  end
  devise_for :users
  resources :films
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "films#index" # главная страница сайтов
  get  '/calc/', to: 'calculators#calc'
  # get '/films/', to: 'films#hello'
  get '/filmtest/', to: 'filmtests#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/film.rb
class Film < ApplicationRecord
    has_one_attached :photo, dependent: :destroy #добавляем прикрипленние файла
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController
    def calc
        x = params["x"].to_f
        y = params["y"].to_f
        operation = params["operation"]
        (operation == nil) ? @check = false: @check = true
        puts "*"*20
        puts params
        puts "*"*20
        @result = x * y if operation == 'multiply'
        @result = x + y if operation == 'addition'
        @result = x - y if operation == 'subtraction'
        if operation == 'division' && y != 0.0
            @result = x / y 
        end
        @result = x ** y if operation == 'degree'
        if y == 0.0 && operation == 'division'
            @result = "на ноль делить нельзя"
        end 
        puts y == 0.0
        puts @result
        puts x
        puts y 
        puts @check
        # render json: {"result": @result}
    end
end 

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: %i[ show edit update destroy ]
  def hello
  end
  # GET /films or /films.json
  def index
    @films = Film.all
  end

  # GET /films/1 or /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
    @film = Film.find(:all)
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films or /films.json
  def create
    puts "*" * 50
    puts film_params
    puts "*" * 50
    @film = Film.new(comment_params)
    @film.photo.attach(params[:film][:photo])
    
    respond_to do |format|
      if @film.save
        format.html { redirect_to film_url(@film), notice: "Film was successfully created." }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1 or /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to film_url(@film), notice: "Film was successfully updated." }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1 or /films/1.json
  def destroy
    @film.destroy

    respond_to do |format|
      format.html { redirect_to films_url, notice: "Film was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(comment_params)
      if @film.save
        redirect_to new_film_path
      end
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.require(:film).permit(:name, :rating, :year, :link_youtube, :director, :description)
    end
end

app/controllers/filmtests_controller.rb
class FilmtestsController < ApplicationController
    # def index
    #     puts "Привет"
    # end

    def index
        @films = Film.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/calculators/calc.html.erb
<br><center>Калькулятор<br></center>
<% if @check == false %>
    Используйте операции из списка <br>
<% end %>
<p>
Пример запроса: <br>
/calc?x=2.5&y=3.5&operation=degree <br>
<ins>Где x - введите первый аргумент, y - введите второй аргумент, operation - выбор операций, x и y - поумолчанию равны 0 </ins><br> 
<p>
Список операции: <br>
<ol>
    <li> multiply -  умножение; <br>
    <li> addition - сложение; <br>
    <li> subtraction - вычитание; <br>
    <li> division - деление; <br>
    <li> degree - степень; <br> </br>
</ol>
результат = <%= @result %>

app/views/films/_film.html.erb
<div id="<%= dom_id film %>">
  <p>
    <strong>Название:</strong>
    <%= film.name %>
  </p>

  <p>
    <strong>Рейтинг:</strong>
    <%= film.rating %>
  </p>

  <p>
    <strong>Год:</strong>
    <%= film.year %>
  </p>

  <p>
    <strong>Ссылка на источник:</strong>
    <%= film.link_youtube %>
  </p>

  <p>
    <strong>Директор:</strong>
    <%= film.director %>
  </p>

  <p>
    <strong>Описание:</strong>
    <%= film.description %>
  </p>

  <p>
    <strong>Жанр:</strong>
    <%= film.category %>
  </p>
</div>

app/views/films/_form.html.erb
<%= form_with(model: film) do |form| %>
  <% if film.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
        <% film.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label :link_youtube, style: "display: block" %>
    <%= form.text_field :link_youtube %>
  </div>

  <div>
    <%= form.label :director, style: "display: block" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %> 
    <%= form.file_field :photo, label: "Выберите фотографию", multiple: false %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Show this film", @film %> |
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/hello.html.erb
helloworld

app/views/films/index.html.erb
<div class="content">
	<p style="color: green"><%= notice %></p>

	<h1>Films</h1>

	<div id="films">
	<% @films.each do |film| %>
		<div class="info_film"><img src="assets/img/inter.png">
			<%= film.description %>
			<div class="button"><a href="show.html">Смотреть</a></div>
		</div>

		<p>
		<%= link_to "Show this film", film %>
		<hr>
		</p>
	<% end %>
	</div>

	<%= link_to "New film", new_film_path %>
</div>

app/views/films/new.html.erb
<h1>New film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="content">
    <h1><%= @film.name %></h1>
    <iframe width="560" height="315" src="<%= @film.link_youtube %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <div class="info_film_page">
        <span class="lable">Рейтинг: </span><span class="value"><%= @film.rating %></span>
        <span class="lable">Год: </span><span class="value"><%= @film.year %></span>
        <span class="lable">Режиссёр: </span><span class="value"><%= @film.director %></span>
    </div>
    <hr>
    <h2>Описание Матрицы</h2>
    <div class="descriptions_film">
        <img src="assets/img/matrix.png">
        <%= @film.description %>
    </div>
    <hr>
    <h2>Отзывы об Матрице:</h2>
    <div class="reviews">
        <div class="review_name">
            Сергей
        </div>
        <div class="review_text">
            Отличный фильм, 3 часа пролетели не заметно.
        </div>
    </div>

    <div class="reviews">
        <div class="review_name">
            Дмитрий
        </div>
        <div class="review_text">
            После фильма Начало, я с не терпением ждал еще работ от Киано Ривз. Матрица меня впечатлил.
        </div>
    </div>

    <div class="send">
        <form method="post" action="#" id="review">
            <input type="text" name="review_name" placeholder="ваше имя">
            <textarea name="review_text"></textarea>
            <input class="btn" type="submit" value="отправить">
        </form>
    </div>

</div>
  <%= link_to "Edit this film", edit_film_path(@film) %> |
  <%= link_to "Back to films", films_path %>

  <%= button_to "Destroy this film", @film, method: :delete %>
</div>

app/views/filmtests/index.html.erb
<div class="main">
	<div class="header">
		<div class="logo">
			<div class="logo_text">
				<h1><a href="#">Онлайн Кино</a></h1> 
				<h2>Лучшие фильмы здесь</h2>
			</div>
		</div>
		<div class="menubar">
				<ul class="menu">
					<li><a href="index.html">Главная</a></li>
					<li class = "selected"><a href="films.html">Фильмы</a></li>
					<li><a href="serials.html">Сериалы</a></li>
					<li><a href="rating.html">Рейтинг фильмов</a></li>
					<li><a href="contact.html">Контакты</a></li>
					
				</ul>
		</div>
		
	</div>
	<div class="site_content">
		<div class="sidebar_container">
			<div class="sidebar">
				<h2>Поиск</h2>
				<form method="post" action="#" id="search_form" >
					<input type="search" name="search_field" placeholder="ваш запрос" />
					<input type="submit" class="btn" value="найти" />
				</form>
			</div>
			<div class="sidebar">
				<h2>Вход</h2>
				<form method="post" action="#" id="login">

					<input type="text" name="login_field" placeholder="логин" />
					<input type="password" name="password_field" placeholder="пароль" />
					<input type="submit" class="btn" value="вход" />
					<div class="lables_passreg_text">
						<span><a href="#">забыли пароль?</a></span> | <span><a href="#">регистрация</a></span>
					</div>

			</div>
			<div class="sidebar">
				<h2>Новости</h2>
				<span>31.02.2018</span>
				<p>Мы запустили расширенный поиск</p>
				<a href="#">читать</a>

			</div>
			<div class="sidebar">
				<h2>Рейтинг фильмов</h2>
				<ul>
					<li><a href="show.html">Интерстеллар</a><span class="rating_sidebar">8.6</span></li>
					<li><a href="#">Матрица</a><span class="rating_sidebar">8.5</span></li>
					<li><a href="#">Безумный Макс</a><span class="rating_sidebar">8.4</span></li>
					<li><a href="#">Облачный Атлас</a><span class="rating_sidebar">8.1</span></li>
				</ul>
			</div>
		</div>
		<div class="content">
			<% @films.each do |film| %>
				<h1><%= film.name %></h1>
				<iframe width="560" height="315" src="<%= film.link_youtube %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
				<div class="info_film_page">
					<span class="lable">Рейтинг: </span><span class="value"><%= film.rating %></span>
					<span class="lable">Год: </span><span class="value"><%= film.year %></span>
					<span class="lable">Режиссёр: </span><span class="value"><%= film.director %></span>
				</div>
				<hr>
				<h2>Описание фильма: <%= film.name %></h2>
				<div class="descriptions_film">
					<img src="assets/img/matrix.png">
					<%= film.description %>
				</div>
				<hr>
				<h2>Отзывы о фильме: <%= film.name %></h2>
				<div class="reviews">
					<div class="review_name">
						Сергей
					</div>
					<div class="review_text">
						Отличный фильм, 3 часа пролетели не заметно.
					</div>
				</div>

				<div class="reviews">
					<div class="review_name">
						Дмитрий
					</div>
					<div class="review_text">
						После фильма Начало, я с не терпением ждал еще работ от Киано Ривз. Матрица меня впечатлил.
					</div>
				</div>

				<div class="send">
					<form method="post" action="#" id="review">
						<input type="text" name="review_name" placeholder="ваше имя">
						<textarea name="review_text"></textarea>
						<input class="btn" type="submit" value="отправить">
					</form>
				</div>
			<%end %>
		</div>
	</div>
	<div class="footer">
		<p>
			<a href="#">Главная</a>
			<a href="#">Фильмы</a>
			<a href="#">Сериалы</a>
			<a href="#">Рейтинг Фильмов</a>
			<a href="#">Контакты</a>
		</p>
		<p>
			Даниил.com 2021
		</p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rybu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "style" %>
  </head>

  <body>   
	<div class="main">
		<div class="header">
			<div class="logo">
				<div class="logo_text">
					<h1><a href="#">Онлайн Кино</a></h1> 
					<h2>Лучшие фильмы здесь</h2>
				</div>
			</div>
			<div class="menubar">
					<ul class="menu">
						<li><a href="index.html">Главная</a></li>
						<li class = "selected"><a href="films.html">Фильмы</a></li>
						<li><a href="serials.html">Сериалы</a></li>
						<li><a href="rating.html">Рейтинг фильмов</a></li>
						<li><a href="contact.html">Контакты</a></li>
						
					</ul>
			</div>
			
		</div>
		<div class="site_content">
			<div class="sidebar_container">
				<div class="sidebar">
					<h2>Поиск</h2>
					<form method="post" action="#" id="search_form" >
                        <input type="search" name="search_field" placeholder="ваш запрос" />
                        <input type="submit" class="btn" value="найти" />
                    </form>
				</div>
				<div class="sidebar">
					<h2>Вход</h2>
					<form method="post" action="#" id="login">

                        <input type="text" name="login_field" placeholder="логин" />
                        <input type="password" name="password_field" placeholder="пароль" />
                        <input type="submit" class="btn" value="вход" />
                        <div class="lables_passreg_text">
                            <span><a href="#">забыли пароль?</a></span> | <span><a href="#">регистрация</a></span>
                        </div>

				</div>
				<div class="sidebar">
					<h2>Новости</h2>
					<span>31.02.2018</span>
                    <p>Мы запустили расширенный поиск</p>
                    <a href="#">читать</a>

				</div>
				<div class="sidebar">
					<h2>Рейтинг фильмов</h2>
					<ul>
						<li><a href="show.html">Интерстеллар</a><span class="rating_sidebar">8.6</span></li>
						<li><a href="#">Матрица</a><span class="rating_sidebar">8.5</span></li>
						<li><a href="#">Безумный Макс</a><span class="rating_sidebar">8.4</span></li>
						<li><a href="#">Облачный Атлас</a><span class="rating_sidebar">8.1</span></li>
					</ul>
				</div>
			</div>
			<%= render 'shared/nav_bar' %>
		    <p class="notice"><%= notice %></p>
		    <p class="alert"><%= alert %></p>
		    <%= yield %>
		</div>
		<div class="footer">
			<p>
				<a href="#">Главная</a>
				<a href="#">Фильмы</a>
				<a href="#">Сериалы</a>
				<a href="#">Рейтинг Фильмов</a>
				<a href="#">Контакты</a>
			</p>
			<p>
				Даниил.com 2021
			</p>
		</div>
	</div>
  </body>
</html>

app/views/shared/_nav_bar.html.erb
<% if user_signed_in? %>
Вошёл
<%= button_to "Log out", destroy_user_session_path, method: :delete %>
<% else %>
Не вошёл
<a href="<%= new_user_session_path %>">Войти</a> 
<% end %>